stages:
    - test

test:cargo:
    image: "rust:latest"
    stage: test
    script:
        - rustc --version && cargo --version
        - cargo check
        - cargo test
        - cargo test --release
