language: rust
rust:
  - stable
  - beta
  - nightly
env:
  -
  - CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_AVX=
    CARGO_CFG_LATEXESCAPE_DISABLE_AUTO_AVX=
  - CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD=
    CARGO_CFG_LATEXESCAPE_DISABLE_AUTO_SIMD=
matrix:
  allow_failures:
    - rust: nightly
    - env: STAGE=benches
  include:
    - rust: stable
      env: STAGE=benches
    - rust: nightly
      env: STAGE=coverage
    - rust: nightly
      env: STAGE=benches
    - rust: nightly
      env:
        - STAGE=benches
        - CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_AVX=
        - CARGO_CFG_LATEXESCAPE_DISABLE_AUTO_AVX=
    - rust: nightly
      env:
        - STAGE=benches
        - CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD=
        - CARGO_CFG_LATEXESCAPE_DISABLE_AUTO_SIMD=
cache: cargo

before_script:
  - if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
      rustup component add rustfmt;
    fi

script:
  - |
    if [[ -z "$STAGE" ]]; then
    cargo test
    cargo build --release --verbose
    fi
  - if [[ "${TRAVIS_RUST_VERSION}" == "stable" ]]; then
      cargo fmt -- --check;
    fi

after_success:
  - |
    if [[ "$STAGE" == "coverage" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install -f cargo-tarpaulin
    RUST_BACKTRACE=1 cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
    echo "Uploaded code coverage"
    fi
  - |
    if [[ "$STAGE" == "benches" ]] && [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    cd benches && \
    cargo bench --features with-compare;
    fi
  - |
    if [[ "$STAGE" == "benches" ]] && [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    cd benches && \
    cargo bench --features with-rocket,with-compare;
    fi
