[package]
name = "v_latexescape"
version = "0.4.1"
authors = ["Rust-iendo Barcelona <riendocontributions@gmail.com>"]
description = "The simd optimized LaTeX escaping code"
documentation = "https://docs.rs/v_latexescape"
keywords = ["latex", "escaping", "simd"]
homepage = "https://github.com/rust-iendo/v_htmlescape"
repository = "https://github.com/rust-iendo/v_htmlescape"
license = "MIT/Apache-2.0"
readme = "README.md"
workspace = ".."
edition = "2018"

[badges]
appveyor = { repository = "botika/v_htmlescape" }
maintenance = { status = "actively-developed" }
travis-ci = { repository =  "rust-iendo/v_htmlescape", branch = "master" }
codecov = { repository = "rust-iendo/v_htmlescape", branch = "master", service = "github" }

[lib]
name = "v_latexescape"
path = "src/lib.rs"
bench = false

[dependencies]
v_escape = { version = "0.7", path = "../v_escape" }
cfg-if = "0.1"

[build-dependencies]
v_escape = { version = "0.7", path = "../v_escape" }
